### ISSUE TITLE
AttributeError: module 'datasets.util.map_utils' has no attribute 'get_explored_grid'

### ISSUE THREAD

**Issue by VishnuDuttSharma** [ggeorgak11/UPEN#2]
Hi,

When I run the test command, i.e.
`python main.py --name test_pointnav_exp --ensemble_dir path/to/ensemble/dir --root_path /path/to/dir/containing/habitat-lab --log_dir /path/to/logs --scenes_list 2azQ1b91cZZ --gpu_capacity 1 --with_rrt_planning --test_set v2 `,

I get the following error: 
`AttributeError: module 'datasets.util.map_utils' has no attribute 'get_explored_grid'`.

Searching through the file browser shows that the function is not defined. Could you please help fix this issue?

**Comment by ggeorgak11** [comment]
Thanks for pointing that out. I pushed a fix.
